### ISSUE TITLE
White page flash

### ISSUE THREAD

**Issue by kuchenstrudel** [RubenVanEldik/hackerdaily-frontend#3]
You seem to insert a white page flash on every load.

**Comment by RubenVanEldik** [comment]
Do you see a white page flash during the initial render or every time you go to a different page on HackerDaily?

**Comment by kuchenstrudel** [comment]
Initial render, and when you click the source and go back you see it again.

**Comment by RubenVanEldik** [comment]
Thank you for pointing this out! 

I found the cause of the white page flash and fixed it with commit `d27e7f`.

**Comment by kuchenstrudel** [comment]
> I found the cause of the white page flash and fixed it with commit `d27e7f`.

The issue is still present on Firefox.

On Chrome it also appears on first page load.

**Comment by RubenVanEldik** [comment]
Is the website in dark mode? Because you might see a white flash if you're in dark mode, since the CSS with the `prefers-color-scheme` media query is needed to make the page dark and this is loaded after the initial HTML.

**Comment by RubenVanEldik** [comment]
I submitted a feature request in the Nuxt.js repository. (https://github.com/nuxt/nuxt.js/issues/8580) This issue is quite hard to fix on my own, but its quite easy to fix with the current settings in the Nuxt.js repository.

**Comment by kuchenstrudel** [comment]
> 
> 
> Is the website in dark mode? Because you might see a white flash if you're in dark mode, since the CSS with the `prefers-color-scheme` media query is needed to make the page dark and this is loaded after the initial HTML.

Yes, dark mode.

**Comment by RubenVanEldik** [comment]
Ok! Great to know, now I know for sure where source of the issue is. As soon as there is a good fix in Nuxt.js I'll fix it. :)

**Comment by kuchenstrudel** [comment]
Seems to be fixed now, thank you! 👍
